on: workflow_dispatch

jobs:
  deploy_app_job:
    runs-on: ubuntu-latest
    name: Upload app using argocd
    container: argoproj/argocd:v2.6.5
    steps:
     - name: Login in argocd      
       run: argocd version
    
