on: workflow_dispatch

jobs:
  deploy_app_job:
    runs-on: ubuntu-latest
    name: A job to upload app using argocd
    container: argoproj/argocli
    steps:
     - name: Login in argocd      
       run: |
         argocd login SERVER --username admin --password xD
    
